export const providers = {
	Apple: {
		name: 'Apple',
		importName: 'AppleProvider',
		path: 'apple',
		id: 'APPLE_ID',
		secret: 'APPLE_SECRET',
	},
	Atlassian: {
		name: 'Atlassian',
		importName: 'AtlassianProvider',
		path: 'atlassian',
		id: 'ATLASSIAN_ID',
		secret: 'ATLASSIAN_SECRET',
	},
	Auth0: {
		name: 'Auth0',
		importName: 'Auth0Provider',
		path: 'auth0',
		id: 'AUTH0_ID',
		secret: 'AUTH0_SECRET',
		issuer: 'AUTH0_ISSUER',
	},
	Authentik: {
		name: 'Authentik',
		importName: 'AuthentikProvider',
		path: 'authentik',
		id: 'AUTHENTIK_ID',
		secret: 'AUTHENTIK_SECRET',
	},
	AzureAD: {
		name: 'AzureAD',
		importName: 'AzureADProvider',
		path: 'azure-ad',
		id: 'AZUREAD_ID',
		secret: 'AZUREAD_SECRET',
	},
	AzureB2C: {
		name: 'AzureB2C',
		importName: 'AzureADB2CProvider',
		path: 'azure-ad-b2c',
		id: 'AZUREB2C_ID',
		secret: 'AZUREB2C_SECRET',
	},
	Battlenet: {
		name: 'Battlenet',
		importName: 'BattleNetProvider',
		path: 'battlenet',
		id: 'BN_ID',
		secret: 'BN_ISSUER',
	},
	Box: {
		name: 'Box',
		importName: 'BoxProvider',
		path: 'box',
		id: 'BOX_ID',
		secret: 'BOX_SECRET',
	},
	BoxyHQSAML: {
		name: 'BoxyHQSAML',
		importName: 'BoxyHQSAMLProvider',
		path: 'boxyhq-saml',
		id: 'BOXYHQ_ID',
		secret: 'BOXYHQ_SECRET',
		issuer: 'BOXYHQ_ISSUER',
	},
	Bungie: {
		name: 'Bungie',
		importName: 'BungieProvider',
		path: 'bungie',
		id: 'BUNGIE_ID',
		secret: 'BUNGIE_SECRET',
	},
	Cognito: {
		name: 'Cognito',
		importName: 'CognitoProvider',
		path: 'cognito',
		id: 'COGNITO_ID',
		secret: 'COGNITO_SECRET',
	},
	Coinbase: {
		name: 'Coinbase',
		importName: 'CoinbaseProvider',
		path: 'coinbase',
		id: 'COINBASE_ID',
		secret: 'COINBASE_SECRET',
	},
	Discord: {
		name: 'Discord',
		importName: 'DiscordProvider',
		path: 'discord',
		id: 'DISCORD_ID',
		secret: 'DISCORD_SECRET',
	},
	Dropbox: {
		name: 'Dropbox',
		importName: 'DropboxProvider',
		path: 'dropbox',
		id: 'DROPBOX_ID',
		secret: 'DROPBOX_SECRET',
	},
	DuendeIDS6: {
		name: 'DuendeIDS6',
		importName: 'DuendeIDS6Provider',
		path: 'duende-identity-server6',
		id: 'DUENDEIDS6_ID',
		secret: 'DUENDEIDS6_SECRET',
	},
	Eveonline: {
		name: 'Eveonline',
		importName: 'EVEOnlineProvider',
		path: 'eveonline',
		id: 'EVEONLINE_ID',
		secret: 'EVEONLINE_SECRET',
	},
	Facebook: {
		name: 'Facebook',
		importName: 'FacebookProvider',
		path: 'facebook',
		id: 'FACEBOOK_ID',
		secret: 'FACEBOOK_SECRET',
	},
	Faceit: {
		name: 'Faceit',
		importName: 'FaceItProvider',
		path: 'faceit',
		id: 'FACEIT_ID',
		secret: 'FACEIT_SECRET',
	},
	FortyTwoSchool: {
		name: 'FortyTwoSchool',
		importName: 'FortyTwoProvider',
		path: '42-school',
		id: 'FORTYTWOSCHOOL_ID',
		secret: 'FORTYTWOSCHOOL_SECRET',
	},
	Foursquare: {
		name: 'Foursquare',
		importName: 'FourSquareProvider',
		path: 'foursquare',
		id: 'FOURSQUARE_ID',
		secret: 'FOURSQUARE_SECRET',
	},
	Freshbooks: {
		name: 'Freshbooks',
		importName: 'FreshbooksProvider',
		path: 'freshbooks',
		id: 'FRESHBOOKS_ID',
		secret: 'FRESHBOOKS_SECRET',
	},
	Fusionauth: {
		name: 'Fusionauth',
		importName: 'FusionAuthProvider',
		path: 'fusionauth',
		id: 'FUSIONID',
		secret: 'FUSIONSECRET',
	},
	GitHub: {
		name: 'GitHub',
		importName: 'GitHubProvider',
		path: 'github',
		id: 'GITHUB_ID',
		secret: 'GITHUB_SECRET',
	},
	Gitlab: {
		name: 'Gitlab',
		importName: 'GitlabProvider',
		path: 'gitlb',
		id: 'GITLAB_ID',
		secret: 'GITLAB_SECRET',
	},
	Google: {
		name: 'Google',
		importName: 'GoogleProvider',
		path: 'google',
		id: 'GOOGLE_ID',
		secret: 'GOOGLE_SECRET',
	},
	Hubspot: {
		name: 'Hubspot',
		importName: 'HubspotProvider',
		path: 'hubspot',
		id: 'HUBSPOT_ID',
		secret: 'HUBSPOT_SECRET',
	},
	Instagram: {
		name: 'Instagram',
		importName: 'InstagramProvider',
		path: 'instagram',
		id: 'INSTAGRAM_ID',
		secret: 'INSTAGRAM_SECRET',
	},
	Kakao: {
		name: 'Kakao',
		importName: 'KakaoProvider',
		path: 'kakao',
		id: 'KAKAO_ID',
		secret: 'KAKAO_SECRET',
	},
	Keycloak: {
		name: 'Keycloak',
		importName: 'KeycloakProvider',
		path: 'keycloak',
		id: 'KEYCLOAK_ID',
		secret: 'KEYCLOAK_SECRET',
	},
	Line: {
		name: 'Line',
		importName: 'LineProvider',
		path: 'line',
		id: 'LINE_ID',
		secret: 'LINE_SECRET',
	},
	LinkedIn: {
		name: 'LinkedIn',
		importName: 'LinkedInProvider',
		path: 'linkedin',
		id: 'LINKEDIN_ID',
		secret: 'LINKEDIN_SECRET',
	},
	Mailchimp: {
		name: 'Mailchimp',
		importName: 'MailchimpProvider',
		path: 'mailchimp',
		id: 'MAILCHIMP_ID',
		secret: 'MAILCHIMP_SECRET',
	},
	Mailru: {
		name: 'Mailru',
		importName: 'MailRuProvider',
		path: 'mailru',
		id: 'MAILRU_ID',
		secret: 'MAILRU_SECRET',
	},
	Medium: {
		name: 'Medium',
		importName: 'MediumProvider',
		path: 'medium',
		id: 'MEDIUM_ID',
		secret: 'MEDIUM_SECRET',
	},
	Naver: {
		name: 'Naver',
		importName: 'NaverProvider',
		path: 'naver',
		id: 'NAVER_ID',
		secret: 'NAVER_SECRET',
	},
	Netlify: {
		name: 'Netlify',
		importName: 'NetlifyProvider',
		path: 'netlify',
		id: 'NETLIFY_ID',
		secret: 'NETLIFY_SECRET',
	},
	Okta: {
		name: 'Okta',
		importName: 'OktaProvider',
		path: 'okta',
		id: 'OKTA_ID',
		secret: 'OKTA_SECRET',
	},
	Onelogin: {
		name: 'Onelogin',
		importName: 'OneLoginProvider',
		path: 'onelogin',
		id: 'ONELOGIN_ID',
		secret: 'ONELOGIN_SECRET',
	},
	Osso: {
		name: 'Osso',
		importName: 'OssoProvider',
		path: 'osso',
		id: 'OSSO_ID',
		secret: 'OSSO_SECRET',
		issuer: 'OSSO_ISSUER',
	},
	Osu: {
		name: 'Osu',
		importName: 'OsuProvider',
		path: 'osu',
		id: 'OSU_ID',
		secret: 'OSU_SECRET',
	},
	Passage: {
		name: 'Passage',
		importName: 'PassageProvider',
		path: 'passage',
		id: 'PASSAGE_ID',
		secret: 'PASSAGE_SECRET',
		issuer: 'PASSAGE_ISSUER',
	},
	Patreon: {
		name: 'Patreon',
		importName: 'PatreonProvider',
		path: 'patreon',
		id: 'PATREON_ID',
		secret: 'PATREON_SECRET',
	},
	Pinterest: {
		name: 'Pinterest',
		importName: 'PinterestProvider',
		path: 'pinterest',
		id: 'PINTEREST_ID',
		secret: 'PINTEREST_SECRET',
	},
	Pipedrive: {
		name: 'Pipedrive',
		importName: 'PipedriveProvider',
		path: 'pipedrive',
		id: 'PIPEDRIVE_ID',
		secret: 'PIPEDRIVE_SECRET',
	},
	Reddit: {
		name: 'Reddit',
		importName: 'RedditProvider',
		path: 'reddit',
		id: 'REDDIT_ID',
		secret: 'REDDIT_SECRET',
	},
	Salesforce: {
		name: 'Salesforce',
		importName: 'SalesforceProvider',
		path: 'salesforce',
		id: 'SALESFORCE_ID',
		secret: 'SALESFORCE_SECRET',
	},
	Slack: {
		name: 'Slack',
		importName: 'SlackProvider',
		path: 'slack',
		id: 'SLACK_ID',
		secret: 'SLACK_SECRET',
	},
	Spotify: {
		name: 'Spotify',
		importName: 'SpotifyProvider',
		path: 'spotify',
		id: 'SPOTIFY_ID',
		secret: 'SPOTIFY_SECRET',
	},
	Strava: {
		name: 'Strava',
		importName: 'StravaProvider',
		path: 'strava',
		id: 'STRAVA_ID',
		secret: 'STRAVA_SECRET',
	},
	Todoist: {
		name: 'Todoist',
		importName: 'TodoistProvider',
		path: 'todoist',
		id: 'TODOIST_ID',
		secret: 'TODOIST_SECRET',
	},
	Trakt: {
		name: 'Trakt',
		importName: 'TraktProvider',
		path: 'trakt',
		id: 'TRAKT_ID',
		secret: 'TRAKT_SECRET',
	},
	Twitch: {
		name: 'Twitch',
		importName: 'TwitchProvider',
		path: 'twitch',
		id: 'TWITCH_ID',
		secret: 'TWITCH_SECRET',
	},
	Twitter: {
		name: 'Twitter',
		importName: 'TwitterProvider',
		path: 'twitter',
		id: 'TWITTER_ID',
		secret: 'TWITTER_SECRET',
		version: '2.0',
	},
	UnitedEffects: {
		name: 'UnitedEffects',
		importName: 'UnitedEffectsProvider',
		path: 'united-effects',
		id: 'UE_ID',
		secret: 'UE_SECRET',
		issuer: 'UE_ISSUER',
	},
	Vk: {
		name: 'Vk',
		importName: 'VkProvider',
		path: 'vk',
		id: 'VK_ID',
		secret: 'VK_SECRET',
	},
	Wikimedia: {
		name: 'Wikimedia',
		importName: 'WikimediaProvider',
		path: 'wikimedia',
		id: 'WIKIMEDIA_ID',
		secret: 'WIKIMEDIA_SECRET',
	},
	Wordpress: {
		name: 'Wordpress',
		importName: 'WordpressProvider',
		path: 'wordpress',
		id: 'WORDPRESS_ID',
		secret: 'WORDPRESS_SECRET',
	},
	WorkOS: {
		name: 'WorkOS',
		importName: 'WorkOSProvider',
		path: 'workos',
		id: 'WORKOS_ID',
		secret: 'WORKOS_SECRET',
	},
	Yandex: {
		name: 'Yandex',
		importName: 'YandexProvider',
		path: 'yandex',
		id: 'YANDEX_ID',
		secret: 'YANDEX_SECRET',
	},
	Zitadel: {
		name: 'Zitadel',
		importName: 'ZitadelProvider',
		path: 'zitadel',
		id: 'ZITADEL_ID',
		secret: 'ZITADEL_SECRET',
	},
	Zoho: {
		name: 'Zoho',
		importName: 'ZohoProvider',
		path: 'zoho',
		id: 'ZOHO_ID',
		secret: 'ZOHO_SECRET',
	},
	Zoom: {
		name: 'Zoom',
		importName: 'ZoomProvider',
		path: 'zoom',
		id: 'ZOOM_ID',
		secret: 'ZOOM_SECRET',
	},
};

export const ProviderKeys = (key: keyof typeof providers) => {
	return providers[key];
};
